# Tutorial: Python and Pandas

Welcome to the first tutorial worksheet for Data Science: A First Introduction with Python!  There is a tutorial worksheet like this one corresponding to each chapter of the textbook. This tutorial covers the [Python and Pandas](https://python.datasciencebook.ca/intro.html) chapter of the online textbook, which also lists learning objectives. You should read the textbook chapter before attempting this tutorial worksheet. Tutorial worksheets generally have slightly harder questions than lecture worksheets. Some questions will be manually graded by the TAs, and there are also occasionally "hidden test" questions, where you can't check your answer in advance.

But as always: collaborating on these exercises is more than okay -- it's encouraged!

Any place you see `___`, you must fill in the function, variable, or data to complete the code. Substitute the `None` and the `raise NotImplementedError # No Answer - remove if you provide an answer` with your completed code and answers then proceed to run the cell.

**Revision Question** Match the following definitions with the corresponding functions used in Python:
<br> {points: 1}

*Definitions*

A. Reads the most common types of flat file data, comma separated values. 

B. Filters rows AND selects columns in a single operation

C. Filters rows OR selects columns (but not both at the same time)

D. Adds a new column to a data frame as a function of the old columns.

E. Declares the input data frame for a visualization.

*Functions*

1. `alt.Chart`
2. `loc[]`
3. `[]`
4. `pd.read_csv`
5. `assign`

For each definition, assign the integer corresponding to the correct function to the letter object associated with the defintion. For example:

    B = 1

*Assign your answers to the objects `A`, `B`, `C`, `D`, and `E`. Your answers should each be a single integer.*

In [ ]:
# Your Answer Here

In [3]:
from hashlib import sha1
assert sha1(str(type(A)).encode("utf-8")+b"e18f1").hexdigest() == "51e657e428b9a734d4d5f4fafa9a47eb683dab8e", "type of A is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(A).encode("utf-8")+b"e18f1").hexdigest() == "f6a845b0d22ed2ab1da6c4237da1e6ef940b8a1d", "value of A is not correct"

assert sha1(str(type(B)).encode("utf-8")+b"e18f2").hexdigest() == "cec51fa33343dadce48fbe379efd65893f4de121", "type of B is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(B).encode("utf-8")+b"e18f2").hexdigest() == "37fecdfb49eb4fb9eb8c4049909f46e3022f7637", "value of B is not correct"

assert sha1(str(type(C)).encode("utf-8")+b"e18f3").hexdigest() == "4c60cf69d3d420f312d5823c1d9e7ec4541d7cd0", "type of C is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(C).encode("utf-8")+b"e18f3").hexdigest() == "623da7f7d002c59dabaca79f0a6868c9293b62fb", "value of C is not correct"

assert sha1(str(type(D)).encode("utf-8")+b"e18f4").hexdigest() == "dd076cdcb4b23c37b1500b4559e4a1e2c0a30777", "type of D is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(D).encode("utf-8")+b"e18f4").hexdigest() == "79d82a358742b9beb5f8cbe7e530832cfccfb499", "value of D is not correct"

assert sha1(str(type(E)).encode("utf-8")+b"e18f5").hexdigest() == "7c04f28653ab91f459c9572a45d20fed15978bf2", "type of E is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(E).encode("utf-8")+b"e18f5").hexdigest() == "cf956d9f388e937cd1cd5665f0b00290af4a0fd7", "value of E is not correct"

print('Success!')

Success!

## 1. Vickers and Vertosick Exercise
We hope you haven't forgotten about them just yet! As you might recall from lecture, Vickers and Vertosick were the researchers that wanted to study different factors affecting race performance of recreational runners. They assembled a data set that includes the age, sex, and Body Mass Index (BMI) of runners, comparing it with their timed performance (how long it took them to complete either 5 or 10 km runs).

We will be continuing our analysis of their data to practice what you learnt during the previous lecture. The goal for today, however, is to produce a plot of BMI against the time **(in minutes)** it took for participants **under the age of 35** to run 5 kilometres. To do this, we will need to complete the following steps:

1. use `loc[]` to extract the rows where age is less than 35 and select the `bmi` and `km5_time_seconds` columns 
2. use `assign` to create a new column with 5 km race time in minutes rather than seconds
3. use `Altair` to create our plot of BMI (x-axis) and race time in minutes (y-axis)

**Tips for success:** Try going through all of the steps on your own, but don't forget to discuss with others (classmates, TAs, or an instructor) if you get stuck. If something is wrong and you can't spot the issue, be sure to **read the error message carefully**. Since there are a lot of steps involved in working with data and modifying it, feel free to look back at the worksheet from this week for assistance.

**Question 1.1** Multiple Choice
<br> {points: 1}

After reading the text above what column do you think we will be using for our threshold when we extract the rows of runners under 35 years old? 

A. `age`

B. `km5_time_seconds`

C. `bmi`

D. `sex`

*Assign your answer to an object called `answer1_1`. Make sure to write the uppercase letter for the answer you have chosen and surround the letter with quotes.*

In [ ]:
# Make sure the correct answer is an uppercase letter.
# Surround your answer with quotation marks.

In [5]:
from hashlib import sha1
assert sha1(str(type(answer1_1)).encode("utf-8")+b"dc859").hexdigest() == "d5153f09cd7d1c205729942551f9f22d3466df48", "type of answer1_1 is not str. answer1_1 should be an str"
assert sha1(str(len(answer1_1)).encode("utf-8")+b"dc859").hexdigest() == "fcab68f0dd1c77aee35013660b7506642e5aaa84", "length of answer1_1 is not correct"
assert sha1(str(answer1_1.lower()).encode("utf-8")+b"dc859").hexdigest() == "a9d579fd44636b7fac2b1bbe15a5e93278b4a289", "value of answer1_1 is not correct"
assert sha1(str(answer1_1).encode("utf-8")+b"dc859").hexdigest() == "90422e1850f5a26f0826d41715249146457991fd", "correct string value of answer1_1 but incorrect case of letters"

print('Success!')

Success!

**Question 1.2** True or False
<br> {points: 1}

We will be selecting the columns `age` and `km5_time_seconds` to plot. True or false?

*Make sure your answer is either `True` or `False` to an object called `answer1_2`*

In [ ]:
# Make sure your answer is either True or False

In [7]:
from hashlib import sha1
assert sha1(str(type(answer1_2)).encode("utf-8")+b"5c19e").hexdigest() == "50ad7864b742696ed38ef9508973c5168132edff", "type of answer1_2 is not bool. answer1_2 should be a bool"
assert sha1(str(answer1_2).encode("utf-8")+b"5c19e").hexdigest() == "1b81df22d809da656f3f9109d843125d6ceec180", "boolean value of answer1_2 is not correct"

print('Success!')

Success!

**Question 1.3** Multiple Choice
<br> {points: 1}

Select the answer with the correct order of functions that we will use to wrangle our data into a useable form and plot it.

A. `assign`, `loc[]`, `alt.Chart`

B. `alt.Chart`, `loc[]`, `assign`

C. `loc[]`, `assign`, `alt.Chart`

D. `assign`, `alt.Chart`, `loc[]`

*Assign your answer to an object called `answer1_3`. Make sure your answer is an uppercase letter and is surrounded by quotation marks (e.g. `"F"`).*

In [ ]:
# Your Answer Here

In [9]:
from hashlib import sha1
assert sha1(str(type(answer1_3)).encode("utf-8")+b"bb313").hexdigest() == "122cc8627d59e768e5c61ba197e952758c397f4e", "type of answer1_3 is not str. answer1_3 should be an str"
assert sha1(str(len(answer1_3)).encode("utf-8")+b"bb313").hexdigest() == "c16625f1ca83ccf9489e6f3b079d07aa80930550", "length of answer1_3 is not correct"
assert sha1(str(answer1_3.lower()).encode("utf-8")+b"bb313").hexdigest() == "bafc7bd0714292796ffab4113f5a4b09743071db", "value of answer1_3 is not correct"
assert sha1(str(answer1_3).encode("utf-8")+b"bb313").hexdigest() == "929effe134eef35c7218e7c37ba88abefc0035ce", "correct string value of answer1_3 but incorrect case of letters"

print('Success!')

Success!

**Question 1.4** 
<br> {points: 1}

To work on the cells below, import the `pandas` package as `pd`. If you have difficulty with importing this package, revisit `worksheet_intro` and read over Section 5 (Packages).

In [ ]:
import sys

# Your Code Here

In [11]:
from hashlib import sha1
assert sha1(str(type(('pandas' in sys.modules))).encode("utf-8")+b"c8f0").hexdigest() == "33a5adf0b0a8154ac86c05e25d284a42338b5fde", "type of ('pandas' in sys.modules) is not bool. ('pandas' in sys.modules) should be a bool"
assert sha1(str(('pandas' in sys.modules)).encode("utf-8")+b"c8f0").hexdigest() == "adeb7536bca031964bb20e41d3893796c22751e5", "boolean value of ('pandas' in sys.modules) is not correct"

assert sha1(str(type((pd.__name__ == 'pandas'))).encode("utf-8")+b"c8f1").hexdigest() == "9370d4e7c1b99489682784335d1d76a51017cb86", "type of (pd.__name__ == 'pandas') is not bool. (pd.__name__ == 'pandas') should be a bool"
assert sha1(str((pd.__name__ == 'pandas')).encode("utf-8")+b"c8f1").hexdigest() == "61f945fc2bd94ffa3011f46a21d27a368a463057", "boolean value of (pd.__name__ == 'pandas') is not correct"

print('Success!')

Success!

**Question 1.5** 
<br> {points: 1}

With the proper package loaded, you can now read in the data from the file "marathon_small.csv" and assign it to an object called `marathon_small`.
To help you along the way, we have provded some scaffolding for you to build on.
Uncomment (remove the `#`) the scaffolded code and replace each occurence of `___` with the relevant code to solve this exercise.

In [ ]:
# ___ = ___("marathon_small.csv")

       age        bmi  km5_time_seconds  km10_time_seconds     sex
0     25.0  21.622116               NaN             2798.0  female
1     41.0  23.905970            1210.0                NaN    male
2     25.0  21.640728             994.0                NaN    male
3     35.0  23.592323            1075.0             2135.0    male
4     34.0  22.706404            1186.0                NaN    male
...    ...        ...               ...                ...     ...
1828  32.0  22.727272               NaN             2591.0  female
1829  55.0  20.585695            1157.0             2771.0    male
1830  42.0  23.747681            1203.0                NaN    male
1831  23.0  24.209032            2040.0                NaN  female
1832  58.0  23.491768            1304.0             2819.0    male

[1833 rows x 5 columns]

In [13]:
from hashlib import sha1
assert sha1(str(type(marathon_small['sex'].dtype)).encode("utf-8")+b"cb15b").hexdigest() == "2b8524b724000c6a96eee6bbb40c4dbbe960e907", "type of marathon_small['sex'].dtype is not correct"
assert sha1(str(marathon_small['sex'].dtype).encode("utf-8")+b"cb15b").hexdigest() == "fbd64f6c0ab2bdf5a7ccaf16835317b7a8ba2f96", "value of marathon_small['sex'].dtype is not correct"

assert sha1(str(type(marathon_small)).encode("utf-8")+b"cb15c").hexdigest() == "57a2e1cc2c91564e36408587a581c71bec2d86a9", "type of type(marathon_small) is not correct"

assert sha1(str(type(marathon_small.shape)).encode("utf-8")+b"cb15d").hexdigest() == "7daa1476b15a9557f267ca5153aa7214e1fd7c72", "type of marathon_small.shape is not tuple. marathon_small.shape should be a tuple"
assert sha1(str(len(marathon_small.shape)).encode("utf-8")+b"cb15d").hexdigest() == "e45de418980f0db7c9b951329ecc8ee616584cf7", "length of marathon_small.shape is not correct"
assert sha1(str(sorted(map(str, marathon_small.shape))).encode("utf-8")+b"cb15d").hexdigest() == "c5e99284f5368ea25c0dd9cc55ecc7f81c22f0bf", "values of marathon_small.shape are not correct"
assert sha1(str(marathon_small.shape).encode("utf-8")+b"cb15d").hexdigest() == "f3043d2bb274967b40c6d5bb43a06cac23246859", "order of elements of marathon_small.shape is not correct"

assert sha1(str(type(sum(marathon_small.age))).encode("utf-8")+b"cb15e").hexdigest() == "e8805f24080cfb3d0d5690e49d26c2e7b4efcfe2", "type of sum(marathon_small.age) is not float. Please make sure it is float and not np.float64, etc. You can cast your value into a float using float()"
assert sha1(str(round(sum(marathon_small.age), 2)).encode("utf-8")+b"cb15e").hexdigest() == "37787f4a678df860b768c7a56cd2486a1c1ed396", "value of sum(marathon_small.age) is not correct (rounded to 2 decimal places)"

assert sha1(str(type(marathon_small.columns.values)).encode("utf-8")+b"cb15f").hexdigest() == "01f0758b92feb087a51dd0df36a33e36b95f4a63", "type of marathon_small.columns.values is not correct"
assert sha1(str(marathon_small.columns.values).encode("utf-8")+b"cb15f").hexdigest() == "4430b55a3926ec6f667b53ed57f365a12415a5e9", "value of marathon_small.columns.values is not correct"

print('Success!')

Success!

**Question 1.6** 
<br> {points: 1}

Use `loc[]` so that information is only included from participants under the age of 35 and the data only contains the columns needed for the plot.

In this exercise we have again provided you with some starter code to help you along the way.
When there are multiple lines of code,
you can highlight them with your pointer
and then press <kbd>Ctrl</kbd> + <kbd>/</kbd> (on Windows and Linux) or <kbd>Cmd</kbd> + <kbd>/</kbd> (on Mac)
to uncomment all the lines at the same time.
You can both comment and uncomment lines with this shortcut;
this is more convenient than adding/deleting the `#` manually!

*Hint: `bmi` is already given to you below. What else do we want to plot?*

*Name the resulting dataframe `marathon_select`*.

In [ ]:
# ___ = ___.loc[
#     marathon_small["___"] < 35,
#     ["bmi", ___]
# ]

            bmi  km5_time_seconds
0     21.622116               NaN
2     21.640728             994.0
4     22.706404            1186.0
6     22.518295            1292.0
8     24.505407            1440.0
...         ...               ...
1822  23.831274            1648.0
1824  18.998579            1486.0
1827  22.626263            1414.0
1828  22.727272               NaN
1831  24.209032            2040.0

[922 rows x 2 columns]

In [15]:
from hashlib import sha1
assert sha1(str(type(marathon_select.shape)).encode("utf-8")+b"dc32f").hexdigest() == "4836707cbb326eb077f04878518c86ba2c02379f", "type of marathon_select.shape is not tuple. marathon_select.shape should be a tuple"
assert sha1(str(len(marathon_select.shape)).encode("utf-8")+b"dc32f").hexdigest() == "c026ab658708ba774b5c8b17fe722b1750aa7bab", "length of marathon_select.shape is not correct"
assert sha1(str(sorted(map(str, marathon_select.shape))).encode("utf-8")+b"dc32f").hexdigest() == "f9ce76bdbe2b566a45ea36859bcb12e92b91d53c", "values of marathon_select.shape are not correct"
assert sha1(str(marathon_select.shape).encode("utf-8")+b"dc32f").hexdigest() == "10e4266aa7a85a68eb0f17fb90fb72f88374bd44", "order of elements of marathon_select.shape is not correct"

assert sha1(str(type(sum(marathon_select.bmi))).encode("utf-8")+b"dc330").hexdigest() == "ac29108591c5f6033f9432c24381d06e64a52fc0", "type of sum(marathon_select.bmi) is not float. Please make sure it is float and not np.float64, etc. You can cast your value into a float using float()"
assert sha1(str(round(sum(marathon_select.bmi), 2)).encode("utf-8")+b"dc330").hexdigest() == "e186d86e97eccde9088b187b4d4bc748a52c0305", "value of sum(marathon_select.bmi) is not correct (rounded to 2 decimal places)"

assert sha1(str(type(sum(marathon_select.km5_time_seconds.dropna()))).encode("utf-8")+b"dc331").hexdigest() == "03b9b84f32ed3baf96775524ccb2635c98a1d4da", "type of sum(marathon_select.km5_time_seconds.dropna()) is not float. Please make sure it is float and not np.float64, etc. You can cast your value into a float using float()"
assert sha1(str(round(sum(marathon_select.km5_time_seconds.dropna()), 2)).encode("utf-8")+b"dc331").hexdigest() == "0b8a36f0c2505d022b3c7e49d28c515ac2753419", "value of sum(marathon_select.km5_time_seconds.dropna()) is not correct (rounded to 2 decimal places)"

print('Success!')

Success!

**Question 1.7** 
<br> {points: 1}

Create a new column called: `km5_time_minutes` which contains the time in minutes rather than seconds.

*Name the result after creating the new column `marathon_exact`.*

In [ ]:
# ___ = marathon_select.assign(km5_time_minutes = ___ / ___)

            bmi  km5_time_seconds  km5_time_minutes
0     21.622116               NaN               NaN
2     21.640728             994.0         16.566667
4     22.706404            1186.0         19.766667
6     22.518295            1292.0         21.533333
8     24.505407            1440.0         24.000000
...         ...               ...               ...
1822  23.831274            1648.0         27.466667
1824  18.998579            1486.0         24.766667
1827  22.626263            1414.0         23.566667
1828  22.727272               NaN               NaN
1831  24.209032            2040.0         34.000000

[922 rows x 3 columns]

In [17]:
assert sha1(str(type(marathon_exact.shape)).encode("utf-8")+b"bcfc8").hexdigest() == "10a2b6863bed138a5b01e91d47172150e2e48dc5", "type of marathon_exact.shape is not tuple. marathon_exact.shape should be a tuple"
assert sha1(str(len(marathon_exact.shape)).encode("utf-8")+b"bcfc8").hexdigest() == "f25d9f1d6ac93de2c9876306d8a2fc18c3077d67", "length of marathon_exact.shape is not correct"
assert sha1(str(sorted(map(str, marathon_exact.shape))).encode("utf-8")+b"bcfc8").hexdigest() == "6a63e57b570a0e24e793661642333425614bf51a", "values of marathon_exact.shape are not correct"
assert sha1(str(marathon_exact.shape).encode("utf-8")+b"bcfc8").hexdigest() == "d98db0bcd7e409e33fa87302e4fbd37e7f0277f7", "order of elements of marathon_exact.shape is not correct"

assert sha1(str(type(sum(marathon_exact.bmi))).encode("utf-8")+b"bcfc9").hexdigest() == "23e4c922f1f57b667695abee0e9d07c8ac132bdd", "type of sum(marathon_exact.bmi) is not float. Please make sure it is float and not np.float64, etc. You can cast your value into a float using float()"
assert sha1(str(round(sum(marathon_exact.bmi), 2)).encode("utf-8")+b"bcfc9").hexdigest() == "a8658d82856bc6bf0e0b0bece5a5df61109c91af", "value of sum(marathon_exact.bmi) is not correct (rounded to 2 decimal places)"

assert sha1(str(type(sum(marathon_exact.km5_time_minutes.dropna()))).encode("utf-8")+b"bcfca").hexdigest() == "ae26bea790a20b2a7f42432b5c8e589c45b38c33", "type of sum(marathon_exact.km5_time_minutes.dropna()) is not float. Please make sure it is float and not np.float64, etc. You can cast your value into a float using float()"
assert sha1(str(round(sum(marathon_exact.km5_time_minutes.dropna()), 2)).encode("utf-8")+b"bcfca").hexdigest() == "f3c8c4604225111f0582b3f4c79db054b8c231ee", "value of sum(marathon_exact.km5_time_minutes.dropna()) is not correct (rounded to 2 decimal places)"

print('Success!')

Success!

**Question 1.8** 
<br> {points: 1}

Now let's generate a scatter plot with the `bmi` on the x-axis and the time in minutes on the y-axis. Assign the plot to a variable called `marathon_plot`.

Ensure that your axis labels are human-readable (do not leave them as default column names).

In [18]:
# run this cell
import altair as alt

In [ ]:
# ___ = ___(marathon_exact).mark_point().encode(
#     x=alt.X(___).title(___),
#     y=___(___).___(___)
# )

In [20]:
# Run this cell to see what your scatterplot looks like!
marathon_plot

alt.Chart(...)

In [21]:
from hashlib import sha1
assert sha1(str(type(marathon_plot.encoding.x['shorthand'])).encode("utf-8")+b"bd596").hexdigest() == "5e61f8017a33f73e6f1d7fc48f64471c0ecc0de6", "type of marathon_plot.encoding.x['shorthand'] is not str. marathon_plot.encoding.x['shorthand'] should be an str"
assert sha1(str(len(marathon_plot.encoding.x['shorthand'])).encode("utf-8")+b"bd596").hexdigest() == "767f3156c33aa6665eddca27b0414689953289a6", "length of marathon_plot.encoding.x['shorthand'] is not correct"
assert sha1(str(marathon_plot.encoding.x['shorthand'].lower()).encode("utf-8")+b"bd596").hexdigest() == "bb96bf4805cad188ac916b0b7af3fc44f867fa16", "value of marathon_plot.encoding.x['shorthand'] is not correct"
assert sha1(str(marathon_plot.encoding.x['shorthand']).encode("utf-8")+b"bd596").hexdigest() == "bb96bf4805cad188ac916b0b7af3fc44f867fa16", "correct string value of marathon_plot.encoding.x['shorthand'] but incorrect case of letters"

assert sha1(str(type(marathon_plot.encoding.y['shorthand'])).encode("utf-8")+b"bd597").hexdigest() == "3a89aa125a0649e49daa33e4eaeb8dcc8ae81d98", "type of marathon_plot.encoding.y['shorthand'] is not str. marathon_plot.encoding.y['shorthand'] should be an str"
assert sha1(str(len(marathon_plot.encoding.y['shorthand'])).encode("utf-8")+b"bd597").hexdigest() == "181c6da99cf661b6ba636be602defcc792086f2b", "length of marathon_plot.encoding.y['shorthand'] is not correct"
assert sha1(str(marathon_plot.encoding.y['shorthand'].lower()).encode("utf-8")+b"bd597").hexdigest() == "26aae5ef1fbaea96c157e221b3266fe76215bb43", "value of marathon_plot.encoding.y['shorthand'] is not correct"
assert sha1(str(marathon_plot.encoding.y['shorthand']).encode("utf-8")+b"bd597").hexdigest() == "26aae5ef1fbaea96c157e221b3266fe76215bb43", "correct string value of marathon_plot.encoding.y['shorthand'] but incorrect case of letters"

assert sha1(str(type(marathon_plot.mark)).encode("utf-8")+b"bd598").hexdigest() == "2ffff6b16297760062d464ef08dc00e82c27301a", "type of marathon_plot.mark is not str. marathon_plot.mark should be an str"
assert sha1(str(len(marathon_plot.mark)).encode("utf-8")+b"bd598").hexdigest() == "54108d7fdaa5cb61475ce092e1329b3f55af6554", "length of marathon_plot.mark is not correct"
assert sha1(str(marathon_plot.mark.lower()).encode("utf-8")+b"bd598").hexdigest() == "31a540abeec294773d4485056490b4a8093f43c6", "value of marathon_plot.mark is not correct"
assert sha1(str(marathon_plot.mark).encode("utf-8")+b"bd598").hexdigest() == "31a540abeec294773d4485056490b4a8093f43c6", "correct string value of marathon_plot.mark but incorrect case of letters"

assert sha1(str(type(isinstance(marathon_plot.encoding.x['title'], str))).encode("utf-8")+b"bd599").hexdigest() == "400a252004037be78df1b63d885a4d7d7d910b49", "type of isinstance(marathon_plot.encoding.x['title'], str) is not bool. isinstance(marathon_plot.encoding.x['title'], str) should be a bool"
assert sha1(str(isinstance(marathon_plot.encoding.x['title'], str)).encode("utf-8")+b"bd599").hexdigest() == "331c4f40bc09cc2e2d741bb4c259803bb2924364", "boolean value of isinstance(marathon_plot.encoding.x['title'], str) is not correct"

assert sha1(str(type(isinstance(marathon_plot.encoding.y['title'], str))).encode("utf-8")+b"bd59a").hexdigest() == "ff7678da9b5c265272f0e61152f77f6acbb3c918", "type of isinstance(marathon_plot.encoding.y['title'], str) is not bool. isinstance(marathon_plot.encoding.y['title'], str) should be a bool"
assert sha1(str(isinstance(marathon_plot.encoding.y['title'], str)).encode("utf-8")+b"bd59a").hexdigest() == "16f27c0c9f5cfa05d1722e508ff4866d2c48714d", "boolean value of isinstance(marathon_plot.encoding.y['title'], str) is not correct"

print('Success!')

Success!

**Question 1.9** 
<br> {points: 3}

Which option below **best** describes the plot above? 

A. For runners under the age of 35, there is no relationship at all between BMI and the time it takes to complete a 5 km race . 

B. For runners under 35, we see that as BMI increases the time it takes to complete a 5 km race increases. This suggests that there is a positive relationship between these two variables for runners under 35 in this data set. 

C. For runners under 35, we see that as BMI increases the time it takes to complete a 5 km decreases. This suggests that there is a negative relationship between these two variables for runners under 35 in this data set.

*Assign your answer to an object called `answer1_9`. Make sure your answer is an uppercase letter and is surrounded by quotation marks (e.g. `"F"`).*

In [ ]:
# Your Answer Here

In [23]:
from hashlib import sha1
assert sha1(str(type(answer1_9)).encode("utf-8")+b"d00b9").hexdigest() == "aef8dbdfccc1b94931a89049adcc18d23b4bf186", "type of answer1_9 is not str. answer1_9 should be an str"
assert sha1(str(len(answer1_9)).encode("utf-8")+b"d00b9").hexdigest() == "4d21d51972760dfd31af406ed03280860c467419", "length of answer1_9 is not correct"
assert sha1(str(answer1_9.lower()).encode("utf-8")+b"d00b9").hexdigest() == "d22bddebb4d8810f9688b937d7d0324ac50344fe", "value of answer1_9 is not correct"
assert sha1(str(answer1_9).encode("utf-8")+b"d00b9").hexdigest() == "6acdd8b25b5fc4d03c3c2e3635232bba8091e8a0", "correct string value of answer1_9 but incorrect case of letters"

print('Success!')

Success!

**Question 1.10**
<br> {points: 1}

Now explore the relationship between the **age** of all runners and the time taken to complete the 5 km run (in minutes again). Using the original `marathon_small` data frame, mutate the `km5_time_seconds` column such that it is in minutes and name the new column `km5_time_minutes`. Save the resulting data frame to an object called `marathon_small_mins`.

Next, create a scatter plot (similar to the one in Question 1.9) but this time have `age` on the x-axis. Assign your plot to an object called `age_vs_time`.

There is a lot missing from the cell below (no hints were given). Try working on it on your own before looking at earlier questions in this tutorial or worksheet_intro. 

*Don't forget to label your axes! Where appropriate, axes labels should also include units (for example, the axis that maps to the column `age` should have the unit "years").*

In [ ]:
# Your Code Here

alt.Chart(...)

In [25]:
from hashlib import sha1
assert sha1(str(type(marathon_small_mins.columns.to_numpy())).encode("utf-8")+b"ba593").hexdigest() == "16345d3bd527e583f4441eee40009479985fd92c", "type of marathon_small_mins.columns.to_numpy() is not correct"
assert sha1(str(marathon_small_mins.columns.to_numpy()).encode("utf-8")+b"ba593").hexdigest() == "d0b2f6e1a316c596e6233a2b9730c801459b2fa4", "value of marathon_small_mins.columns.to_numpy() is not correct"

assert sha1(str(type(age_vs_time.encoding.x['shorthand'])).encode("utf-8")+b"ba594").hexdigest() == "daccfbde1693ab4c0517f5f7add8fa2698b40288", "type of age_vs_time.encoding.x['shorthand'] is not str. age_vs_time.encoding.x['shorthand'] should be an str"
assert sha1(str(len(age_vs_time.encoding.x['shorthand'])).encode("utf-8")+b"ba594").hexdigest() == "0b82bb19532373120407c884949572e5c553c99c", "length of age_vs_time.encoding.x['shorthand'] is not correct"
assert sha1(str(age_vs_time.encoding.x['shorthand'].lower()).encode("utf-8")+b"ba594").hexdigest() == "234fd4b21ae939503e5d417b0f214dd47e568d05", "value of age_vs_time.encoding.x['shorthand'] is not correct"
assert sha1(str(age_vs_time.encoding.x['shorthand']).encode("utf-8")+b"ba594").hexdigest() == "234fd4b21ae939503e5d417b0f214dd47e568d05", "correct string value of age_vs_time.encoding.x['shorthand'] but incorrect case of letters"

assert sha1(str(type(age_vs_time.encoding.y['shorthand'])).encode("utf-8")+b"ba595").hexdigest() == "b16b6014cde7bfa88bdbd0ca44b7e342994b90a4", "type of age_vs_time.encoding.y['shorthand'] is not str. age_vs_time.encoding.y['shorthand'] should be an str"
assert sha1(str(len(age_vs_time.encoding.y['shorthand'])).encode("utf-8")+b"ba595").hexdigest() == "cf82a0bb4611d366c34b959edf864221bdb39922", "length of age_vs_time.encoding.y['shorthand'] is not correct"
assert sha1(str(age_vs_time.encoding.y['shorthand'].lower()).encode("utf-8")+b"ba595").hexdigest() == "b6849ff822e6d01eb200186aeb1a82934ac7dc06", "value of age_vs_time.encoding.y['shorthand'] is not correct"
assert sha1(str(age_vs_time.encoding.y['shorthand']).encode("utf-8")+b"ba595").hexdigest() == "b6849ff822e6d01eb200186aeb1a82934ac7dc06", "correct string value of age_vs_time.encoding.y['shorthand'] but incorrect case of letters"

assert sha1(str(type(age_vs_time.mark)).encode("utf-8")+b"ba596").hexdigest() == "669100015de0621063969b8191fb9c7dcf96d039", "type of age_vs_time.mark is not str. age_vs_time.mark should be an str"
assert sha1(str(len(age_vs_time.mark)).encode("utf-8")+b"ba596").hexdigest() == "21d311a32c6478d36d26d5e4798232a891c3f8b1", "length of age_vs_time.mark is not correct"
assert sha1(str(age_vs_time.mark.lower()).encode("utf-8")+b"ba596").hexdigest() == "cb23fc7164fea7a2605a11df9233baa0ec013bb9", "value of age_vs_time.mark is not correct"
assert sha1(str(age_vs_time.mark).encode("utf-8")+b"ba596").hexdigest() == "cb23fc7164fea7a2605a11df9233baa0ec013bb9", "correct string value of age_vs_time.mark but incorrect case of letters"

assert sha1(str(type(isinstance(age_vs_time.encoding.x['title'], str))).encode("utf-8")+b"ba597").hexdigest() == "c4c9a59feb37e41a6832e148b5085cc2ecb92e7a", "type of isinstance(age_vs_time.encoding.x['title'], str) is not bool. isinstance(age_vs_time.encoding.x['title'], str) should be a bool"
assert sha1(str(isinstance(age_vs_time.encoding.x['title'], str)).encode("utf-8")+b"ba597").hexdigest() == "737e5afff6694c560e03b6d2e84524f1d55ba8e5", "boolean value of isinstance(age_vs_time.encoding.x['title'], str) is not correct"

assert sha1(str(type(isinstance(age_vs_time.encoding.y['title'], str))).encode("utf-8")+b"ba598").hexdigest() == "d1cca84884742b517970c90d47077882fab69e85", "type of isinstance(age_vs_time.encoding.y['title'], str) is not bool. isinstance(age_vs_time.encoding.y['title'], str) should be a bool"
assert sha1(str(isinstance(age_vs_time.encoding.y['title'], str)).encode("utf-8")+b"ba598").hexdigest() == "9fef565f2fa671c358407a793ea65572063d4813", "boolean value of isinstance(age_vs_time.encoding.y['title'], str) is not correct"

print('Success!')

Success!

**Question 1.11**
<br> {points: 3}

In the plot above, we can see a positive relationship between age and time taken to complete a 5 km run. Is this relationship strong (points are close together) or weak (points are more widely scattered)? 

Assign your answer (either `"weak"` or `"strong"`) to an object called `answer1_11`. Make sure to write in all lower-case and surround your answer with quotes.

In [ ]:
# Your Answer Here

In [27]:
from hashlib import sha1
assert sha1(str(type(answer1_11)).encode("utf-8")+b"4572e").hexdigest() == "666b17019afd72ee5ccdc07d7ad6750317dd4d47", "type of answer1_11 is not str. answer1_11 should be an str"
assert sha1(str(len(answer1_11)).encode("utf-8")+b"4572e").hexdigest() == "2362db2da6c93c60b37b26b51965d387c696e25c", "length of answer1_11 is not correct"
assert sha1(str(answer1_11.lower()).encode("utf-8")+b"4572e").hexdigest() == "64bc066783ffebf4b42dc9aafb00d44e452a2995", "value of answer1_11 is not correct"
assert sha1(str(answer1_11).encode("utf-8")+b"4572e").hexdigest() == "64bc066783ffebf4b42dc9aafb00d44e452a2995", "correct string value of answer1_11 but incorrect case of letters"

print('Success!')

Success!

## 2. Bike-Sharing

Climate change, and solutions to mitigate it, is currently on the tongues and minds of many people. One healthy and environmentally friendly transportation alternative that has been recently gaining popularity is bike-sharing. Apart from their extensive real-world applications in improving health and creating more climate-friendly transit, the data generated by these bike-sharing systems makes them great for research. In contrast to bus and subway transit systems, bike-share transit systems precisely document where a trip starts, where it ends, and how long it lasts, for each individual using the system. This level of individual traceability may allow for better detection of mobility patterns in cities and possible detection of important events.

Today, we will be analyzing [data obtained from Capital Bikeshare](http://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset#), a bike-sharing system from Washington, DC. The temperature data (in units of degrees Celsius) has been normalized from the original range so that all values fall between 0 and 1 (a common data processing technique helpful for some machine/statistical learning tools). Our goal is to determine if there is a relationship between temperature and the number of people renting bikes during the Spring (March 20th - June 21st).

**Question 2.1** Multiple Choice
<br> {points: 1}

In comparison to bike-sharing systems, why aren't other modes of transportation as useful when it comes to acquiring data?

A. Not as fast. 

B. Documentation isn't as precise. 

C. Not as environmentally friendly. 

D. Bus drivers don't cooperate. 

*Assign your answer to an object called: `answer2_1`. Make sure your answer is an uppercase letter and is surrounded by quotation marks (e.g. `"F"`).*

In [ ]:
# Your Answer Here

In [29]:
from hashlib import sha1
assert sha1(str(type(answer2_1)).encode("utf-8")+b"38ccf").hexdigest() == "d4b71c3b04ec1a482c1428e548a5346483ea11ed", "type of answer2_1 is not str. answer2_1 should be an str"
assert sha1(str(len(answer2_1)).encode("utf-8")+b"38ccf").hexdigest() == "c94a2fee50a205e02f3aa157b1c3933ea31edb2f", "length of answer2_1 is not correct"
assert sha1(str(answer2_1.lower()).encode("utf-8")+b"38ccf").hexdigest() == "e5ee65d92963e3b7fb2a7fef11d1da51f046f454", "value of answer2_1 is not correct"
assert sha1(str(answer2_1).encode("utf-8")+b"38ccf").hexdigest() == "745c8ad9f5e3f2440798e93100acbb8dcf691e8a", "correct string value of answer2_1 but incorrect case of letters"

print('Success!')

Success!

**Question 2.2** Multiple Choice
<br> {points: 1}

What are the units for the normalized temperature?

A. Kelvin

B. Fahrenheit 

C. Celsius 

*Assign your answer to an object called: `answer2_2`. Make sure your answer is an uppercase letter and is surrounded by quotation marks (e.g. `"F"`).*

In [ ]:
# Your Answer Here

In [31]:
from hashlib import sha1
assert sha1(str(type(answer2_2)).encode("utf-8")+b"8d903").hexdigest() == "45f12abbc227756a90802f5eed2fcd87a376b491", "type of answer2_2 is not str. answer2_2 should be an str"
assert sha1(str(len(answer2_2)).encode("utf-8")+b"8d903").hexdigest() == "d4bd8bfa104c56fb3578e51b5690dd1f7826d980", "length of answer2_2 is not correct"
assert sha1(str(answer2_2.lower()).encode("utf-8")+b"8d903").hexdigest() == "bee017a0a1e3e7a91efb7a11c220880b77812c2c", "value of answer2_2 is not correct"
assert sha1(str(answer2_2).encode("utf-8")+b"8d903").hexdigest() == "ff5b7c158ed82999ea1e3941f088e7b50c576ebe", "correct string value of answer2_2 but incorrect case of letters"

print('Success!')

Success!

**Question 2.3** 
<br> {points: 1}

Since we already have `pandas` imported and ready to use, the first step is to read our new data. Add in the missing function and symbol to complete the cell below. Make sure to assign your answer to `bike_data`.

In [ ]:
# ___ = ___("bike_share.csv")

     temperature  casual_users  registered_users  season
0       0.344167           331               654  Spring
1       0.363478           131               670  Spring
2       0.196364           120              1229  Spring
3       0.200000           108              1454  Spring
4       0.226957            82              1518  Spring
..           ...           ...               ...     ...
726     0.254167           247              1867  Spring
727     0.253333           644              2451  Spring
728     0.253333           159              1182  Spring
729     0.255833           364              1432  Spring
730     0.215833           439              2290  Spring

[731 rows x 4 columns]

In [33]:
from hashlib import sha1
assert sha1(str(type(bike_data)).encode("utf-8")+b"967b6").hexdigest() == "c18f470436b13934dc7a074ac5bb6e5d0ba0b378", "type of type(bike_data) is not correct"

assert sha1(str(type(bike_data.shape)).encode("utf-8")+b"967b7").hexdigest() == "d22a7ba9c913a723dcc50efa29b4193463bf7399", "type of bike_data.shape is not tuple. bike_data.shape should be a tuple"
assert sha1(str(len(bike_data.shape)).encode("utf-8")+b"967b7").hexdigest() == "dd657d2ab359cfe8cadc05eb4c34e34afadad771", "length of bike_data.shape is not correct"
assert sha1(str(sorted(map(str, bike_data.shape))).encode("utf-8")+b"967b7").hexdigest() == "ceb54fd03b8795123d98ff370c65086495c226f9", "values of bike_data.shape are not correct"
assert sha1(str(bike_data.shape).encode("utf-8")+b"967b7").hexdigest() == "3603ad78004b9584707c884708df5514d1a84321", "order of elements of bike_data.shape is not correct"

assert sha1(str(type(sum(bike_data.casual_users))).encode("utf-8")+b"967b8").hexdigest() == "83877e43e7fa4f77ecbcdb0a24dc17642e6263be", "type of sum(bike_data.casual_users) is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(sum(bike_data.casual_users)).encode("utf-8")+b"967b8").hexdigest() == "6f2e938917a40dc8876fe20d605a80ab2a0861e7", "value of sum(bike_data.casual_users) is not correct"

assert sha1(str(type(bike_data.columns.values)).encode("utf-8")+b"967b9").hexdigest() == "92d3ecbc70227b320817586a472cd335e2807f3c", "type of bike_data.columns.values is not correct"
assert sha1(str(bike_data.columns.values).encode("utf-8")+b"967b9").hexdigest() == "fdb77180a62503280f65856a3c391301c383a2da", "value of bike_data.columns.values is not correct"

assert sha1(str(type(bike_data.season.dtype)).encode("utf-8")+b"967ba").hexdigest() == "fb3d56661e48bedae06a9901370ab3282b834dec", "type of bike_data.season.dtype is not correct"
assert sha1(str(bike_data.season.dtype).encode("utf-8")+b"967ba").hexdigest() == "21468cf84cf81da6374d5e5a79b38548e142b788", "value of bike_data.season.dtype is not correct"

print('Success!')

Success!

**Question 2.4** 
<br> {points: 1}

Change the data such that you have a new column called `total_users`. 
This column would be the sum of the `casual_users` and the `registered_users`. Assign your answer to an object called `bike_total`.

In [ ]:
# ___ = bike_data.___(___)

     temperature  casual_users  registered_users  season  total_users
0       0.344167           331               654  Spring          985
1       0.363478           131               670  Spring          801
2       0.196364           120              1229  Spring         1349
3       0.200000           108              1454  Spring         1562
4       0.226957            82              1518  Spring         1600
..           ...           ...               ...     ...          ...
726     0.254167           247              1867  Spring         2114
727     0.253333           644              2451  Spring         3095
728     0.253333           159              1182  Spring         1341
729     0.255833           364              1432  Spring         1796
730     0.215833           439              2290  Spring         2729

[731 rows x 5 columns]

In [35]:
from hashlib import sha1
assert sha1(str(type(bike_total.shape)).encode("utf-8")+b"32d94").hexdigest() == "231274dd17fd36288253a0ccebe23a04f4460923", "type of bike_total.shape is not tuple. bike_total.shape should be a tuple"
assert sha1(str(len(bike_total.shape)).encode("utf-8")+b"32d94").hexdigest() == "fb8a3d14e2357403a72b88594610fe6de2cfe1b0", "length of bike_total.shape is not correct"
assert sha1(str(sorted(map(str, bike_total.shape))).encode("utf-8")+b"32d94").hexdigest() == "6e72fe32e8c528663cb9bd0f23989a13cde557ff", "values of bike_total.shape are not correct"
assert sha1(str(bike_total.shape).encode("utf-8")+b"32d94").hexdigest() == "7410ba27f63bf472b6a230609f9f6001fc3d6b3e", "order of elements of bike_total.shape is not correct"

assert sha1(str(type(sum(bike_total.total_users))).encode("utf-8")+b"32d95").hexdigest() == "7cfa28e1fb1f0fdcf6a5674c9fa606a9db096cf5", "type of sum(bike_total.total_users) is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(sum(bike_total.total_users)).encode("utf-8")+b"32d95").hexdigest() == "27ce9d56d6699110669c624fb20f8aec5e1319c7", "value of sum(bike_total.total_users) is not correct"

assert sha1(str(type(sum(bike_total.temperature.dropna()))).encode("utf-8")+b"32d96").hexdigest() == "90e4ffed841fab9f9d6bb6c8dd428a19b7ff39e5", "type of sum(bike_total.temperature.dropna()) is not float. Please make sure it is float and not np.float64, etc. You can cast your value into a float using float()"
assert sha1(str(round(sum(bike_total.temperature.dropna()), 2)).encode("utf-8")+b"32d96").hexdigest() == "91cccc519c0028116795e25cbcefaceb61eb1325", "value of sum(bike_total.temperature.dropna()) is not correct (rounded to 2 decimal places)"

print('Success!')

Success!

**Question 2.5** 
<br> {points: 1}

Filter out the data to include information about rentals that were only made during `Spring`. Name your answer `bike_filter`. Remember that since we are only filtering rows without selecting columns at the same time, you can use `[]` here.

In [ ]:
# ___ = bike_total[___[___] == "Spring"]

     temperature  casual_users  registered_users  season  total_users
0       0.344167           331               654  Spring          985
1       0.363478           131               670  Spring          801
2       0.196364           120              1229  Spring         1349
3       0.200000           108              1454  Spring         1562
4       0.226957            82              1518  Spring         1600
..           ...           ...               ...     ...          ...
726     0.254167           247              1867  Spring         2114
727     0.253333           644              2451  Spring         3095
728     0.253333           159              1182  Spring         1341
729     0.255833           364              1432  Spring         1796
730     0.215833           439              2290  Spring         2729

[181 rows x 5 columns]

In [37]:
from hashlib import sha1
assert sha1(str(type(bike_filter.season.unique())).encode("utf-8")+b"c4749").hexdigest() == "16e87fd0e3f6d8fbc1b1938b3ee05537c6092acd", "type of bike_filter.season.unique() is not correct"
assert sha1(str(bike_filter.season.unique()).encode("utf-8")+b"c4749").hexdigest() == "3e9d0b2bb68895621da0c34a40a8703db25e1bf6", "value of bike_filter.season.unique() is not correct"

assert sha1(str(type(bike_filter.shape)).encode("utf-8")+b"c474a").hexdigest() == "83fc2e68d24afd90e2f0332240d2df6a247292ba", "type of bike_filter.shape is not tuple. bike_filter.shape should be a tuple"
assert sha1(str(len(bike_filter.shape)).encode("utf-8")+b"c474a").hexdigest() == "21cff66fd037d020bb5137a16ca8159e0693ff04", "length of bike_filter.shape is not correct"
assert sha1(str(sorted(map(str, bike_filter.shape))).encode("utf-8")+b"c474a").hexdigest() == "cb6e9a17ac586789e93ef1dbbae339ec15592987", "values of bike_filter.shape are not correct"
assert sha1(str(bike_filter.shape).encode("utf-8")+b"c474a").hexdigest() == "dd44da066f082120ff0fa8ed62b6006516414621", "order of elements of bike_filter.shape is not correct"

assert sha1(str(type(sum(bike_filter.total_users))).encode("utf-8")+b"c474b").hexdigest() == "8739b85a0e843bbf2d28f95c4c3b17030a1431b5", "type of sum(bike_filter.total_users) is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(sum(bike_filter.total_users)).encode("utf-8")+b"c474b").hexdigest() == "99d547c123e05b2d6a54f23fd02dcfea96589cb4", "value of sum(bike_filter.total_users) is not correct"

assert sha1(str(type(sum(bike_filter.temperature.dropna()))).encode("utf-8")+b"c474c").hexdigest() == "7bc355ba5234446982b28dec81a013f72d39c8f3", "type of sum(bike_filter.temperature.dropna()) is not float. Please make sure it is float and not np.float64, etc. You can cast your value into a float using float()"
assert sha1(str(round(sum(bike_filter.temperature.dropna()), 2)).encode("utf-8")+b"c474c").hexdigest() == "cc6916a1fa0f7fa76d1ca7a8328b74dd4a4a38c1", "value of sum(bike_filter.temperature.dropna()) is not correct (rounded to 2 decimal places)"

print('Success!')

Success!

**Question 2.6** 
<br> {points: 3}

Select the columns from the data that we wish to plot. Name your answer `bike_select`. Remember that since we are only selecting columns and not filtering rows at the same time, you can use `[]` here. Also note that selecting columns prior to the plotting step is not strictly necessary and this exercise is more for you to practice the column selection syntax.

*Hint: if you have forgetten, scroll up and re-read the introduction to this exercise.*

In [ ]:
# ___ = ___.loc[:,[___,___]]

     temperature  total_users
0       0.344167          985
1       0.363478          801
2       0.196364         1349
3       0.200000         1562
4       0.226957         1600
..           ...          ...
726     0.254167         2114
727     0.253333         3095
728     0.253333         1341
729     0.255833         1796
730     0.215833         2729

[181 rows x 2 columns]

In [39]:
from hashlib import sha1
assert sha1(str(type(bike_select.shape)).encode("utf-8")+b"58489").hexdigest() == "088222938114f38997035706c052ca69ab25c298", "type of bike_select.shape is not tuple. bike_select.shape should be a tuple"
assert sha1(str(len(bike_select.shape)).encode("utf-8")+b"58489").hexdigest() == "1741d8c5e93c62aeea058206475360c17f5df869", "length of bike_select.shape is not correct"
assert sha1(str(sorted(map(str, bike_select.shape))).encode("utf-8")+b"58489").hexdigest() == "13d5abd1367e60cb8266e0d68f7a3def27b3f33c", "values of bike_select.shape are not correct"
assert sha1(str(bike_select.shape).encode("utf-8")+b"58489").hexdigest() == "3ab81e68e8ee6ef2b71455e1be1a6a2b9f1c268f", "order of elements of bike_select.shape is not correct"

assert sha1(str(type(sum(bike_select.total_users))).encode("utf-8")+b"5848a").hexdigest() == "27fcb1cf5550afe27de09fd696d9fd931492b714", "type of sum(bike_select.total_users) is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(sum(bike_select.total_users)).encode("utf-8")+b"5848a").hexdigest() == "4e2f983ecf4c924dde78a342e2ee8fed20c36c03", "value of sum(bike_select.total_users) is not correct"

assert sha1(str(type(sum(bike_select.temperature.dropna()))).encode("utf-8")+b"5848b").hexdigest() == "1a6192cc21e7c4476e3b8f71d1e9a76a07673fb1", "type of sum(bike_select.temperature.dropna()) is not float. Please make sure it is float and not np.float64, etc. You can cast your value into a float using float()"
assert sha1(str(round(sum(bike_select.temperature.dropna()), 2)).encode("utf-8")+b"5848b").hexdigest() == "29a5a603841aae1df27dff769124181ad9b1cb56", "value of sum(bike_select.temperature.dropna()) is not correct (rounded to 2 decimal places)"

print('Success!')

Success!

**Question 2.7** 
<br> {points: 3}

Plot the data as a scatter plot. 

There is a lot missing from the cell below (no hints were given). Try completing this on your own before looking back at any previous exercises. Assign your plot to an object called `bike_plot_spring`.

*Hint: what do you think should be the x-axis / y-axis? Don't forget to label your axes! Where appropriate, axes labels should also include units (for example, the axis mapped to the `temperature` column should have the units "normalized degrees Celsius").*

In [ ]:
# Your Code Here

alt.Chart(...)

In [41]:
from hashlib import sha1
assert sha1(str(type(bike_plot_spring.encoding.x['shorthand'])).encode("utf-8")+b"57").hexdigest() == "76f0d963085005a0ade3535fde772bc377f81d92", "type of bike_plot_spring.encoding.x['shorthand'] is not str. bike_plot_spring.encoding.x['shorthand'] should be an str"
assert sha1(str(len(bike_plot_spring.encoding.x['shorthand'])).encode("utf-8")+b"57").hexdigest() == "30b601f0cbe127b082649fe6fcd93fa86c798107", "length of bike_plot_spring.encoding.x['shorthand'] is not correct"
assert sha1(str(bike_plot_spring.encoding.x['shorthand'].lower()).encode("utf-8")+b"57").hexdigest() == "07d64fdca5a1600a55d75244cc6a35e643865c71", "value of bike_plot_spring.encoding.x['shorthand'] is not correct"
assert sha1(str(bike_plot_spring.encoding.x['shorthand']).encode("utf-8")+b"57").hexdigest() == "07d64fdca5a1600a55d75244cc6a35e643865c71", "correct string value of bike_plot_spring.encoding.x['shorthand'] but incorrect case of letters"

assert sha1(str(type(bike_plot_spring.encoding.y['shorthand'])).encode("utf-8")+b"58").hexdigest() == "a12c03fc77af30171032de40e3a78c8795e8d685", "type of bike_plot_spring.encoding.y['shorthand'] is not str. bike_plot_spring.encoding.y['shorthand'] should be an str"
assert sha1(str(len(bike_plot_spring.encoding.y['shorthand'])).encode("utf-8")+b"58").hexdigest() == "9bd7909ea32c89f68e82ed0cbe1f30a2e1d72b1c", "length of bike_plot_spring.encoding.y['shorthand'] is not correct"
assert sha1(str(bike_plot_spring.encoding.y['shorthand'].lower()).encode("utf-8")+b"58").hexdigest() == "df2def465450798fd1c16a7f7c4da9ebfe52a461", "value of bike_plot_spring.encoding.y['shorthand'] is not correct"
assert sha1(str(bike_plot_spring.encoding.y['shorthand']).encode("utf-8")+b"58").hexdigest() == "df2def465450798fd1c16a7f7c4da9ebfe52a461", "correct string value of bike_plot_spring.encoding.y['shorthand'] but incorrect case of letters"

assert sha1(str(type(bike_plot_spring.mark)).encode("utf-8")+b"59").hexdigest() == "03c89daa08f904d81e14b8a9e49e0087eada08dc", "type of bike_plot_spring.mark is not str. bike_plot_spring.mark should be an str"
assert sha1(str(len(bike_plot_spring.mark)).encode("utf-8")+b"59").hexdigest() == "2473f01571bf0dcb7d2b16d67da6dd031769947d", "length of bike_plot_spring.mark is not correct"
assert sha1(str(bike_plot_spring.mark.lower()).encode("utf-8")+b"59").hexdigest() == "12562c7b4083a5017afbd5a2293c7a8f53c627aa", "value of bike_plot_spring.mark is not correct"
assert sha1(str(bike_plot_spring.mark).encode("utf-8")+b"59").hexdigest() == "12562c7b4083a5017afbd5a2293c7a8f53c627aa", "correct string value of bike_plot_spring.mark but incorrect case of letters"

assert sha1(str(type(isinstance(bike_plot_spring.encoding.x['title'], str))).encode("utf-8")+b"5a").hexdigest() == "a166d125ddef5320907d58dfe0d368f5c4aa575d", "type of isinstance(bike_plot_spring.encoding.x['title'], str) is not bool. isinstance(bike_plot_spring.encoding.x['title'], str) should be a bool"
assert sha1(str(isinstance(bike_plot_spring.encoding.x['title'], str)).encode("utf-8")+b"5a").hexdigest() == "fbfb940fd3f3d5eadf469f4bed08252c1e9a992c", "boolean value of isinstance(bike_plot_spring.encoding.x['title'], str) is not correct"

assert sha1(str(type(isinstance(bike_plot_spring.encoding.y['title'], str))).encode("utf-8")+b"5b").hexdigest() == "698e7b42b63704972ce21f80580f399f7fe8aa2f", "type of isinstance(bike_plot_spring.encoding.y['title'], str) is not bool. isinstance(bike_plot_spring.encoding.y['title'], str) should be a bool"
assert sha1(str(isinstance(bike_plot_spring.encoding.y['title'], str)).encode("utf-8")+b"5b").hexdigest() == "0c55ded8b91d434c44a338904ee8115ec7075faa", "boolean value of isinstance(bike_plot_spring.encoding.y['title'], str) is not correct"

print('Success!')

Success!

**Question 2.8** 
<br> {points: 3}

In 1-2 sentences, describe whether there is a relationship between the variables observed in the scatterplot of the data for the spring season. Comment on the direction and the strength of the relationship (if there is one), and how the variables change with respect to each other (if they do).

DOUBLE CLICK TO EDIT THIS CELL AND REPLACE THIS TEXT WITH YOUR ANSWER.

## 3. Bike-Sharing Continued

For this exercise, we are going to continue working with Capital Bikeshare dataset. This part of the tutorial will focus on your understanding of how the functions work and test your ability to write code without hints. Note that we have also intentionally decreased the number of auto-graded questions for the remainder of the tutorial.

Unlike the previous exercise, we now want to determine if there is a relationship between temperature and the amount of people renting bikes during Fall (September 22nd - December 21st).  

*Try completing this Exercise from start to finish without any outside help. If you are struggling with a particular question, look at Exercise 2 for assistance.*

**Question 3.1** Multiple Choice
<br> {points: 1}

Which column is going to be filtered during this exercise?

A. `casual_users`

B. `season`

C. `temperature`

D. `total_users`

*Assign your answer to an object called `answer3_1`. Make sure your answer is an uppercase letter and is surrounded by quotation marks (e.g. `"F"`).*

In [ ]:
# Your Answer Here

In [43]:
from hashlib import sha1
assert sha1(str(type(answer3_1)).encode("utf-8")+b"e9b7").hexdigest() == "10ba902fcd4573280135bbcdc2b798a802ffba6e", "type of answer3_1 is not str. answer3_1 should be an str"
assert sha1(str(len(answer3_1)).encode("utf-8")+b"e9b7").hexdigest() == "87c6c47ff04bb42bb58da2d95326f24ffe56d928", "length of answer3_1 is not correct"
assert sha1(str(answer3_1.lower()).encode("utf-8")+b"e9b7").hexdigest() == "515c530077b74d6a99ab6aacb8f50a55730b034d", "value of answer3_1 is not correct"
assert sha1(str(answer3_1).encode("utf-8")+b"e9b7").hexdigest() == "c30dc9eb149e912012541fa5b835264c02f2752a", "correct string value of answer3_1 but incorrect case of letters"

print('Success!')

Success!

**Question 3.2** 
<br> {points: 3}

Recall that the `pandas` package has loaded and the data has already been read. The next step is to change the data such that we have information on all the users. Make sure to save your answer to an object called `bike_total`, and make sure to create a column called `total_users`.

In [ ]:
# Your Code Here

     temperature  casual_users  registered_users  season  total_users
0       0.344167           331               654  Spring          985
1       0.363478           131               670  Spring          801
2       0.196364           120              1229  Spring         1349
3       0.200000           108              1454  Spring         1562
4       0.226957            82              1518  Spring         1600
..           ...           ...               ...     ...          ...
726     0.254167           247              1867  Spring         2114
727     0.253333           644              2451  Spring         3095
728     0.253333           159              1182  Spring         1341
729     0.255833           364              1432  Spring         1796
730     0.215833           439              2290  Spring         2729

[731 rows x 5 columns]

In [45]:
from hashlib import sha1
assert sha1(str(type(("total_users" in bike_total.columns))).encode("utf-8")+b"f191d").hexdigest() == "af56d0584242786d97c12888f0e516f883162abf", "type of (\"total_users\" in bike_total.columns) is not bool. (\"total_users\" in bike_total.columns) should be a bool"
assert sha1(str(("total_users" in bike_total.columns)).encode("utf-8")+b"f191d").hexdigest() == "63b38197a722d1e55c455da60151494edcbc7380", "boolean value of (\"total_users\" in bike_total.columns) is not correct"

assert sha1(str(type(bike_total.shape)).encode("utf-8")+b"f191e").hexdigest() == "f69c0b5748b52a499620c21212095fc563e4b5ea", "type of bike_total.shape is not tuple. bike_total.shape should be a tuple"
assert sha1(str(len(bike_total.shape)).encode("utf-8")+b"f191e").hexdigest() == "0d612c2abc2cabeab551138c8ffe83fba2e9039e", "length of bike_total.shape is not correct"
assert sha1(str(sorted(map(str, bike_total.shape))).encode("utf-8")+b"f191e").hexdigest() == "ddfab62e614481e421f662ea68faaa983a55b14b", "values of bike_total.shape are not correct"
assert sha1(str(bike_total.shape).encode("utf-8")+b"f191e").hexdigest() == "89b833850b40ace72f40b84b365e057129fa9e51", "order of elements of bike_total.shape is not correct"

assert sha1(str(type(bike_total.columns)).encode("utf-8")+b"f191f").hexdigest() == "9eb79a05e1073668e8ef1b4e68b93d31e0bb8c91", "type of bike_total.columns is not correct"
assert sha1(str(bike_total.columns).encode("utf-8")+b"f191f").hexdigest() == "61f9bc4a180ce70f9897259666095e5d95dbe993", "value of bike_total.columns is not correct"

assert sha1(str(type(sum(bike_total.total_users))).encode("utf-8")+b"f1920").hexdigest() == "070c0991662e99ec0ce2629996377d8186a1fcb9", "type of sum(bike_total.total_users) is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(sum(bike_total.total_users)).encode("utf-8")+b"f1920").hexdigest() == "34ad1fb761bfe11c5d7c6b0afe779f7685c04c3a", "value of sum(bike_total.total_users) is not correct"

print('Success!')

Success!

**Question 3.3** 
<br> {points: 3}

Filter out the data to include information about rentals that were only made during `Fall` and select the columns we wish to plot. Name your answer variable `bike_selected`. Use the appropriate operation to do both the row filtering and columns selection in one go.

In [ ]:
# Your Code Here

     temperature  total_users
171     0.680833         4835
172     0.733333         4507
173     0.728333         4790
174     0.724167         4991
175     0.695000         5202
..           ...          ...
626     0.623333         4073
627     0.552500         7591
628     0.546667         7720
629     0.599167         8167
630     0.650000         8395

[188 rows x 2 columns]

In [47]:
from hashlib import sha1
assert sha1(str(type(bike_selected.columns)).encode("utf-8")+b"e0cf0").hexdigest() == "12bd3d46b8c4dad4c742401266294f6475995e49", "type of bike_selected.columns is not correct"
assert sha1(str(bike_selected.columns).encode("utf-8")+b"e0cf0").hexdigest() == "8fa3e9eda6bce917e7b3487313e2196e89272506", "value of bike_selected.columns is not correct"

assert sha1(str(type(bike_selected.shape)).encode("utf-8")+b"e0cf1").hexdigest() == "65a033ea305687a62f1ce4ebd4c1d7db37d26900", "type of bike_selected.shape is not tuple. bike_selected.shape should be a tuple"
assert sha1(str(len(bike_selected.shape)).encode("utf-8")+b"e0cf1").hexdigest() == "f4eeed6e8a1a228a636d7f9ccc57a89312314c8a", "length of bike_selected.shape is not correct"
assert sha1(str(sorted(map(str, bike_selected.shape))).encode("utf-8")+b"e0cf1").hexdigest() == "2cc14ad8dd64e5f8d7dff08489cb70a9f39bfff5", "values of bike_selected.shape are not correct"
assert sha1(str(bike_selected.shape).encode("utf-8")+b"e0cf1").hexdigest() == "151816facece2602c557e49caaaa661402139853", "order of elements of bike_selected.shape is not correct"

assert sha1(str(type(sum(bike_selected.total_users))).encode("utf-8")+b"e0cf2").hexdigest() == "cee08ee5dee534a7c307962258f19ef3bc1be78a", "type of sum(bike_selected.total_users) is not int. Please make sure it is int and not np.int64, etc. You can cast your value into an int using int()"
assert sha1(str(sum(bike_selected.total_users)).encode("utf-8")+b"e0cf2").hexdigest() == "8ddc3cf26844f1c3e8ab32d0ba370b640a370564", "value of sum(bike_selected.total_users) is not correct"

print('Success!')

Success!

**Question 3.4** 
<br> {points: 3}

Plot the data as a scatter plot. Label your x-axis: `Temperature (normalized degrees Celsius)` and your y-axis: `Total Users (Casual and Registered)`. Assign your plot to an object called `bike_plot_fall`.

In [ ]:
# Your Code Here

alt.Chart(...)

In [49]:
from hashlib import sha1
assert sha1(str(type(bike_plot_fall.encoding.x['shorthand'])).encode("utf-8")+b"ab6e9").hexdigest() == "7c24510d2a5e2fd5623b26d56fbc8a1db98144ba", "type of bike_plot_fall.encoding.x['shorthand'] is not str. bike_plot_fall.encoding.x['shorthand'] should be an str"
assert sha1(str(len(bike_plot_fall.encoding.x['shorthand'])).encode("utf-8")+b"ab6e9").hexdigest() == "4b5e38bdcb056980189513b07ff228b5e8c43e1d", "length of bike_plot_fall.encoding.x['shorthand'] is not correct"
assert sha1(str(bike_plot_fall.encoding.x['shorthand'].lower()).encode("utf-8")+b"ab6e9").hexdigest() == "34e5a9b105835c8054ade529c945239f6e76555c", "value of bike_plot_fall.encoding.x['shorthand'] is not correct"
assert sha1(str(bike_plot_fall.encoding.x['shorthand']).encode("utf-8")+b"ab6e9").hexdigest() == "34e5a9b105835c8054ade529c945239f6e76555c", "correct string value of bike_plot_fall.encoding.x['shorthand'] but incorrect case of letters"

assert sha1(str(type(bike_plot_fall.encoding.y['shorthand'])).encode("utf-8")+b"ab6ea").hexdigest() == "d41b4b0d693e6d10eb99f3e1c03c041cd7d4c8cf", "type of bike_plot_fall.encoding.y['shorthand'] is not str. bike_plot_fall.encoding.y['shorthand'] should be an str"
assert sha1(str(len(bike_plot_fall.encoding.y['shorthand'])).encode("utf-8")+b"ab6ea").hexdigest() == "d86920a2e2971e2dd2fca769c285ac8931279265", "length of bike_plot_fall.encoding.y['shorthand'] is not correct"
assert sha1(str(bike_plot_fall.encoding.y['shorthand'].lower()).encode("utf-8")+b"ab6ea").hexdigest() == "8f3824e258884f18521df5db2c8a6dd36821f203", "value of bike_plot_fall.encoding.y['shorthand'] is not correct"
assert sha1(str(bike_plot_fall.encoding.y['shorthand']).encode("utf-8")+b"ab6ea").hexdigest() == "8f3824e258884f18521df5db2c8a6dd36821f203", "correct string value of bike_plot_fall.encoding.y['shorthand'] but incorrect case of letters"

assert sha1(str(type(bike_plot_fall.mark)).encode("utf-8")+b"ab6eb").hexdigest() == "50d6c61a995b317d82d20b756303fce121285fbd", "type of bike_plot_fall.mark is not str. bike_plot_fall.mark should be an str"
assert sha1(str(len(bike_plot_fall.mark)).encode("utf-8")+b"ab6eb").hexdigest() == "b30a7fb3d4c2fa9720e424036a64a9185e22e2fe", "length of bike_plot_fall.mark is not correct"
assert sha1(str(bike_plot_fall.mark.lower()).encode("utf-8")+b"ab6eb").hexdigest() == "6977bd9b5ec0dcad7f51ba797e2164f988bce908", "value of bike_plot_fall.mark is not correct"
assert sha1(str(bike_plot_fall.mark).encode("utf-8")+b"ab6eb").hexdigest() == "6977bd9b5ec0dcad7f51ba797e2164f988bce908", "correct string value of bike_plot_fall.mark but incorrect case of letters"

assert sha1(str(type(bike_plot_fall.encoding.x['title'])).encode("utf-8")+b"ab6ec").hexdigest() == "43ab4870ec6265621e0a06ae0e422367dfdf6ff6", "type of bike_plot_fall.encoding.x['title'] is not str. bike_plot_fall.encoding.x['title'] should be an str"
assert sha1(str(len(bike_plot_fall.encoding.x['title'])).encode("utf-8")+b"ab6ec").hexdigest() == "8ac8e3bf64965d4f28de4179223007c546c08b07", "length of bike_plot_fall.encoding.x['title'] is not correct"
assert sha1(str(bike_plot_fall.encoding.x['title'].lower()).encode("utf-8")+b"ab6ec").hexdigest() == "3743f57322ceb55bb7482bbae46481d455f01b1f", "value of bike_plot_fall.encoding.x['title'] is not correct"
assert sha1(str(bike_plot_fall.encoding.x['title']).encode("utf-8")+b"ab6ec").hexdigest() == "bfb77abcfad9cc52e373a01278e9f4b7b6a15181", "correct string value of bike_plot_fall.encoding.x['title'] but incorrect case of letters"

assert sha1(str(type(bike_plot_fall.encoding.y['title'])).encode("utf-8")+b"ab6ed").hexdigest() == "c9c853cbbb7de6c606f11ccc1e815fc8ed2b7ec4", "type of bike_plot_fall.encoding.y['title'] is not str. bike_plot_fall.encoding.y['title'] should be an str"
assert sha1(str(len(bike_plot_fall.encoding.y['title'])).encode("utf-8")+b"ab6ed").hexdigest() == "47600f9fd6eab5b0f1bee419a4d219ae8b091987", "length of bike_plot_fall.encoding.y['title'] is not correct"
assert sha1(str(bike_plot_fall.encoding.y['title'].lower()).encode("utf-8")+b"ab6ed").hexdigest() == "75e9cead4ed48ae8554f7bcf419cd91932b58421", "value of bike_plot_fall.encoding.y['title'] is not correct"
assert sha1(str(bike_plot_fall.encoding.y['title']).encode("utf-8")+b"ab6ed").hexdigest() == "7c6068d31910e3ff5cc6878081082a2883405fc0", "correct string value of bike_plot_fall.encoding.y['title'] but incorrect case of letters"

print('Success!')

Success!

**Question 3.5** 
<br> {points: 3}

In one sentence, describe whether there is a relationship observed in the scatter plot for the fall season, and if so, the direction of that relationship.

DOUBLE CLICK TO EDIT THIS CELL AND REPLACE THIS TEXT WITH YOUR ANSWER.

**Question 3.6** 
<br> {points: 3}

Looking at the scatter plots for the spring and the fall seasons, what difference(s) do you see? Based on these two plots, what might you recommend to this company to increase their users?

DOUBLE CLICK TO EDIT THIS CELL AND REPLACE THIS TEXT WITH YOUR ANSWER.